Repository elastic/apm-agent-android, pull requests merged in 2023-11, with the labels that each got.

#224 post-release: create pull request with the new changes
  build-tools/src/main/java/co/elastic/apm/compile/tools/publishing/tasks/PostDeployTask.java
Labels: agent-mobile, agent-android

#226 chore: enable dependabot version updates of github-actions yaml files
  .github/dependabot.yml
Labels: agent-mobile, agent-android, Team:Automation

#220 Updating the docs
  docs/intro.asciidoc
Labels: agent-mobile, agent-android

#237 Adding exception event to http errors
  CHANGELOG.asciidoc
  android-sdk/src/main/java/co/elastic/apm/android/sdk/traces/http/impl/okhttp/OtelOkHttpEventListener.java
  android-test/android-test-common/src/main/java/co/elastic/apm/android/test/common/spans/verifiers/BaseSpanVerifier.java
  android-test/android-test-common/src/main/java/co/elastic/apm/android/test/common/spans/verifiers/SpanVerifier.java
  android-test/app/src/test/java/co/elastic/apm/android/test/network/okhttp/OkHttpSpansTest.java
Labels: agent-mobile, agent-android

#239 Release 0.12.0
  CHANGELOG.asciidoc
  gradle.properties
Labels: agent-mobile, agent-android

#240 Create catalog-info.yaml
  catalog-info.yaml
Labels: agent-mobile, agent-android, community, triage
