Repository elastic/apm-agent-android, pull requests merged in 2025-04, with the labels that each got.

#435 Bumping otel semconv version
  gradle/libs.versions.toml
Labels: agent-mobile, agent-android

#436 Docs server update
  docs/reference/how-tos.md
  docs/reference/images/find-export-endpoint/3.png
  docs/reference/images/find-export-endpoint/4.png
Labels: agent-mobile, agent-android

#446 Bumping otel java version
  gradle/libs.versions.toml
  sample-app/app/test-rules.pro
Labels: agent-mobile, agent-android

#449 Bumping junit5 version
  .github/workflows/labeler.yml
  build-tools/src/main/kotlin/elastic.android-library.gradle.kts
  build-tools/src/main/kotlin/elastic.java-library.gradle.kts
  gradle/libs.versions.toml
Labels: agent-mobile, agent-android

#452 Prepare release changes
  .github/workflows/prepare-release.yml
Labels: agent-mobile, agent-android

#443 Updating legacy doc
  docs/automatic-instrumentation.asciidoc
  docs/configuration.asciidoc
  docs/faq.asciidoc
  docs/getting-started.asciidoc
  docs/how-tos.asciidoc
  docs/images/find-export-endpoint/1.png
  docs/images/find-export-endpoint/2.png
  docs/images/find-export-endpoint/3.png
  docs/images/find-export-endpoint/4.png
  docs/images/intro/distributed-tracing.png
  docs/images/span-visualization/1.png
  docs/images/span-visualization/2.png
  docs/images/span-visualization/3.png
  docs/index.asciidoc
  docs/intro.asciidoc
  docs/manual-instrumentation.asciidoc
  docs/release-notes.asciidoc
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
  docs/troubleshooting.asciidoc
Labels: agent-mobile, agent-android

#454 Prepare for the next release
  agent-api/metadata/notice.properties
  agent-common/metadata/notice.properties
  agent-plugin/metadata/notice.properties
  agent-sdk/metadata/notice.properties
  docs/release-notes/index.md
  gradle.properties
  instrumentation/api/metadata/notice.properties
  instrumentation/okhttp/bytebuddy/metadata/notice.properties
  instrumentation/okhttp/library/metadata/notice.properties
  instrumentation/okhttp/plugin/metadata/notice.properties
Labels: agent-mobile, agent-android

#455 Updating post release action
  .github/workflows/release.yml
Labels: agent-mobile, agent-android

#458 Setting instrumentation group to all instrumentation subprojects
  build-tools/src/main/java/co/elastic/otel/android/compilation/tools/publishing/ApmPublisherRootPlugin.java
Labels: agent-mobile, agent-android

#466 [DOCS] Specifies no known issues
  docs/release-notes/known-issues.md
Labels: Team:Docs

#467 Fix docs
  docs/reference/configuration.md
  docs/reference/getting-started.md
  docs/reference/how-tos.md
  docs/reference/index.md
  docs/reference/manual-instrumentation.md
Labels: agent-mobile, agent-android

#468 [docs] Fix image paths for docs-assembler
  docs/reference/getting-started.md
  docs/reference/how-tos.md
  docs/reference/index.md
Labels: documentation, agent-mobile, agent-android, Team:Docs, community, triage

#469 ci: group dependabot github action bump
  .github/dependabot.yml
Labels: agent-mobile, agent-android
