Repository elastic/apm-agent-android, pull requests merged in 2025-07, with the labels that each got.

#541 Add redirects
  docs/docset.yml
  docs/redirects.yml
Labels: documentation, agent-mobile, agent-android, community, triage

#548 Clean up
  .DS_Store
  docs/.DS_Store
Labels: agent-mobile, agent-android

#550 Update redirects.yml
  docs/redirects.yml
Labels: agent-mobile, agent-android, community, triage

#553 github(codeowners): robots-ci can review .github/workflows only
  .github/CODEOWNERS
Labels: agent-mobile, agent-android

#566 Bump libs versions
  agent-sdk/src/main/java/co/elastic/otel/android/internal/features/diskbuffering/DiskBufferingManager.kt
  agent-sdk/src/main/java/co/elastic/otel/android/internal/features/diskbuffering/tools/DiskManager.kt
  agent-sdk/src/main/java/co/elastic/otel/android/internal/features/persistence/SimpleTemporaryFileProvider.kt
  agent-sdk/src/test/java/co/elastic/otel/android/internal/features/persistence/DiskManagerTest.kt
  gradle/instrumentation.versions.toml
  gradle/libs.versions.toml
  sample-app/app/test-rules.pro
Labels: agent-mobile, agent-android

#579 Adding min Kotlin version compatibility
  build-tools/src/main/kotlin/elastic.android-library.gradle.kts
  build-tools/src/main/kotlin/elastic.java-library.gradle.kts
  gradle.properties
Labels: agent-mobile, agent-android

#575 catalog-info.yaml: remove apmmachine references
  catalog-info.yaml
Labels: documentation, agent-mobile, agent-android
